AprimoTaskViewer/Models/TaskDetailCancel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailCancel : TaskDetail
    {
    }
}

AprimoTaskViewer/Controllers/TaskDetailCancelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailCancelController : Controller
    {
        private TaskContext db = new TaskContext();

        public ActionResult Search(string SearchBox)
        {
            var canceltasks = from t in db.CancelTasks select t;
            var canceltasks2 = from z in db.CancelTasks select z;

            if (!String.IsNullOrEmpty(SearchBox))
            {
                int value;
                if (int.TryParse(SearchBox, out value))
                {
                    canceltasks2 = from z in db.CancelTasks
                               where
                                    z.FrameNumber.ToString().Equals(SearchBox)
                                    || z.AprimoNumber.ToString().Equals(SearchBox)
                                  //|| z.ManagerId.Equals(SearchBox)
                                  //|| z.StatusId.Equals(SearchBox)
                               select z;
                    return View("Index", canceltasks2.ToList());
                }
                else
                {
                    canceltasks = from t in db.CancelTasks
                               where
                                   t.TaskName.Contains(SearchBox)
                                   || t.employee.ManagerName.Contains(SearchBox)
                                   || t.status.StatusName.Contains(SearchBox)
                               select t;
                }
            }

            //Return List of Tasks Data Rows Based on:
            //Date (boolean) or Textbox String
            canceltasks = canceltasks.AsQueryable().OrderBy("ManagerId ASC, StatusId ASC, FrameNumber ASC");
            return View("Index", canceltasks.ToList());    //(Task Index Page, list of tasks) 
        }

        // GET: TaskDetailCancel
        public ActionResult Index()
        {

            //var canceltasks = from t in db.CancelTasks
            //                  where
            //                      t.status.StatusName.Contains("Cancelled")
            //                  select t;

            var canceltasks = db.CancelTasks.Include(t => t.employee).Include(t => t.status);
            canceltasks = canceltasks.AsQueryable().OrderBy("ManagerId ASC, StatusId ASC, FrameNumber ASC");
            return View(canceltasks.ToList());
        }

        // GET: TaskDetailCancel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskDetailCancel taskDetailCancel = db.CancelTasks.Find(id);
            if (taskDetailCancel == null)
            {
                return HttpNotFound();
            }
            return View(taskDetailCancel);
        }

        // GET: TaskDetailCancel/Create
        public ActionResult Create()
        {
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName");
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName");
            return View();
        }

        // POST: TaskDetailCancel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskDetailId,TaskName,FrameNumber,AprimoNumber,ManagerId,StatusId")] TaskDetailCancel taskDetailCancel)
        {
            if (ModelState.IsValid)
            {
                db.CancelTasks.Add(taskDetailCancel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailCancel.ManagerId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailCancel.StatusId);
            return View(taskDetailCancel);
        }

        // GET: TaskDetailCancel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskDetailCancel taskDetailCancel = db.CancelTasks.Find(id);
            if (taskDetailCancel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailCancel.ManagerId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailCancel.StatusId);
            return View(taskDetailCancel);
        }

        // POST: TaskDetailCancel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskDetailId,TaskName,FrameNumber,AprimoNumber,ManagerId,StatusId")] TaskDetailCancel taskDetailCancel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taskDetailCancel).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailCancel.ManagerId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailCancel.StatusId);
            return View(taskDetailCancel);
        }

        // GET: TaskDetailCancel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskDetailCancel taskDetailCancel = db.CancelTasks.Find(id);
            if (taskDetailCancel == null)
            {
                return HttpNotFound();
            }
            return View(taskDetailCancel);
        }

        // POST: TaskDetailCancel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaskDetailCancel taskDetailCancel = db.CancelTasks.Find(id);
            db.CancelTasks.Remove(taskDetailCancel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AprimoTaskViewer/Views/TaskDetailCancel/Create.cshtml
@model AprimoTaskViewer.Models.TaskDetailCancel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailCancel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AprimoTaskViewer/Views/TaskDetailCancel/Delete.cshtml
@model AprimoTaskViewer.Models.TaskDetailCancel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskDetailCancel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AprimoTaskViewer/Views/TaskDetailCancel/Details.cshtml
@model AprimoTaskViewer.Models.TaskDetailCancel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaskDetailCancel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaskDetailId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AprimoTaskViewer/Views/TaskDetailCancel/Edit.cshtml
@model AprimoTaskViewer.Models.TaskDetailCancel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailCancel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaskDetailId)

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AprimoTaskViewer/Views/TaskDetailCancel/Index.cshtml
@model IEnumerable<AprimoTaskViewer.Models.TaskDetailCancel>
@using AprimoTaskViewer.Helpers;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@*('Search' action method, 'TaskDetailCancel' Controller)*@
@using (Html.BeginForm("Search", "TaskDetailCancel"))
{
    @*input String 'SearchBox' into Action 'Search' - StudentController*@
    @Html.Editor("SearchBox")           @*textbox*@
    <input type="submit" value="Search" />  @*Submit - button ("Search")*@
}
<br><br>

@*CSS3 - alternate row colors*@
<style>
    tr:nth-child(odd) {
        background-color: #eee;
    }

    tr:nth-child(even) {
        background-color: #fff;
    }
</style>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </th>
        <th>
           @Html.DisplayNameFor(model => model.TaskName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.employee.ManagerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status.StatusName)
        </td>
        <td>
            @Html.Truncate(item.TaskName, 20)
            @*@Html.DisplayFor(modelItem => item.TaskName)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FrameNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AprimoNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TaskDetailId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TaskDetailId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TaskDetailId })
        </td>
    </tr>
}

</table>