AprimoTaskViewer/Models/TaskDetailOld.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailOld : TaskDetail
    {
        [Display(Name = "Begin Date")]
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime BeginDate { get; set; }

        [Display(Name = "End Date")]
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        //public static implicit operator TaskDetailOld(TaskDetailNew v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}

AprimoTaskViewer/Controllers/TaskDetailOldController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;
using System.Linq.Dynamic;
using System.Globalization;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailOldController : Controller
    {
        private TaskContext db = new TaskContext();

        [HttpPost]
        public ActionResult deleteRow(IEnumerable<int> aprimoRecordDeletebyId)
        {
            //loop through each selected checkbox and pass this 'id' to selected Datatable rows
            foreach (var id in aprimoRecordDeletebyId)
            {
                var aprimo = db.OldTasks.Single(s => s.TaskDetailId == id);

                db.OldTasks.Remove(aprimo);
            }
            db.SaveChanges();   //after all selected check-boxed data rows are deleted - save changes to database
            return RedirectToAction("Index");
        }

        //Import Excel File For Processing
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile, string statusId)
        {
            //Init. OldTasks and NewTasks
            TaskDetailOld oldTask = new TaskDetailOld();
            //TaskDetailNew newTask = new TaskDetailNew();

 /** Disallow empty/null excel files - send ajax message **/

            if (excelfile == null || excelfile.ContentLength == 0)
            {
                ViewBag.Error = "Please select an excel file";
                return View("Index");
            }

            else
            {
                if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx") || excelfile.FileName.EndsWith("csv"))
                {    
                    /** Logic for extracting excel file's data by uploading it to the local server disk **/       
                    
                    string path = Server.MapPath("~/Content/" + excelfile.FileName);
                    if (System.IO.File.Exists(path))
                        System.IO.File.Delete(path);
                    excelfile.SaveAs(path);

                    //Init. Excel objects
                    Excel.Application app;
                    Excel.Workbook workBook;
                    Excel.Worksheet workSheet;
                    Excel.Range range;

                    //Read the data from the excel file 
                    app = new Excel.Application();
                    workBook = app.Workbooks.Open(path);
                    workSheet = (Excel.Worksheet)workBook.ActiveSheet;
                    range = workSheet.UsedRange;

                    /*DateTime - 'Begin' and 'End'*/
                    DateTime BeginDateTime = new DateTime();
                    DateTime EndDateTime = new DateTime();

                    /*String - 'Begin' and 'End'*/
                    string endDate;
                    string beginDate;

                    //Logic for accessing Frame 5 Excel docs (.xls or .xlsx) - see if file type (.xls(x)) & 'B2' cell == 'Frame 5'
                    //Frame 5
                    if ((excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx")) && ((range.Cells[2, 2]).Text).ToString().Contains("Frame 5"))
                    {

                        for (int row = 5; row < range.Rows.Count; row += 9)
                        {
                            //Get Task Name
                            //oldTask.TaskName = int.Parse(((Excel.Range)range.Cells[row, 2]).Text);
                            if (((range.Cells[row, 2]).Text).ToString() != "")
                                oldTask.TaskName = ((range.Cells[row, 2]).Text).ToString();
                            else if (((range.Cells[row++, 2]).Text).ToString() != "")
                                oldTask.TaskName = ((range.Cells[row++, 2]).Text).ToString();
                            else
                                row = 90001;

                            //Get Begin Date
                            beginDate = ((range.Cells[10, 2]).Text).ToString();
                            BeginDateTime = DateTime.Parse(beginDate);
                            oldTask.BeginDate = BeginDateTime;

                            //Get End Date
                            endDate = ((range.Cells[11, 2]).Text).ToString();
                            EndDateTime = DateTime.Parse(endDate);
                            oldTask.EndDate = EndDateTime;

                            //Compares EndDate to Today's Date
                            if (oldTask.EndDate >= DateTime.Today)
                                oldTask.StatusId = 4;     //running
                            if (oldTask.EndDate < DateTime.Today)
                                oldTask.StatusId = 5;     //completed

                            //Get Frame #
                            oldTask.FrameNumber = 5;

                            //Get AprimoNumber --> OldTask Datatable
                            oldTask.AprimoNumber = int.Parse(((range.Cells[1, 2]).Text).ToString());

                            //Get Manager
                            oldTask.ManagerId = 3;      //Frame 5 - Joe MacFarland    

                            db.OldTasks.Add(oldTask);   //add OldTask row record to DataTable!
                            db.SaveChanges();           //after all excel data rows are added - save changes to Database
                        }
                    }
              //Logic for accessing Frame 1-4 Excel docs (.csv)
                    if (excelfile.FileName.EndsWith("csv"))
                    {
                        //starts at campaign name
                        for (int row = 6; row < range.Rows.Count; row += 11)
                        {
                            //check to see if Campaign name is 'null' then proceed
                            if (((range.Cells[row, 3]).Text).ToString() != "")
                            {
                                //Get Task Name - [6,3] 
                                oldTask.TaskName = ((range.Cells[row, 3]).Text).ToString();

                                //Get Begin Date - [12, 3]
                                beginDate = ((range.Cells[row+=6, 3]).Text).ToString() +
                                            ((range.Cells[row, 5]).Text +",").ToString() +  
                                        ((range.Cells[row, 7]).Text).ToString();

                                BeginDateTime = DateTime.ParseExact(beginDate, "MMMd,yyyy", CultureInfo.CreateSpecificCulture("en-US"));
                                oldTask.BeginDate = BeginDateTime;

                                //Get End Date - [16,3]
                                endDate = ((range.Cells[row += 4, 3]).Text).ToString() +
                                            ((range.Cells[row, 5]).Text +",").ToString() +
                                        ((range.Cells[row, 7]).Text).ToString();

                                //EndDateTime
                                EndDateTime = DateTime.ParseExact(endDate, "MMMd,yyyy", CultureInfo.CreateSpecificCulture("en-US"));
                                oldTask.EndDate = EndDateTime;

                                //Compares EndDate to Today's Date
                                if (oldTask.EndDate >= DateTime.Today)
                                    oldTask.StatusId = 4;     //running
                                if (oldTask.EndDate < DateTime.Today)
                                    oldTask.StatusId = 5;     //completed

                                //Get Frame # - row 25 (16+16)
                                oldTask.FrameNumber = int.Parse(((range.Cells[row += 9, 3]).Text).ToString());

                                //Get AprimoNumber --> OldTask Datatable
                                oldTask.AprimoNumber = int.Parse(((range.Cells[8, 3]).Text).ToString());

                                //Get Manager
                                if (oldTask.TaskName.Contains("Motors") || oldTask.TaskName.Contains("eGW"))
                                {
                                    oldTask.ManagerId = 2; //Cindy Puma   
                                }
                                else if (!oldTask.TaskName.Contains("Motors") && !oldTask.TaskName.Contains("eGW"))
                                {
                                    oldTask.ManagerId = 5; //Sarah Peterson
                                }     

                                db.OldTasks.Add(oldTask);   //add OldTask row record to DataTable!
                                db.SaveChanges();           //after all excel data rows are added - save changes to Database
                            } //end of if (campaign name exists)

                            else
                            {
                                row = 9001; //shitty way off breaking off the loop
                            }

                        }   //end of For Loop
                    }   //end of if

                        //Close Workbook and Quit
                        workBook.Close(true, null, null);
                        app.Quit();

                        releaseObject(workSheet);
                        releaseObject(workBook);
                        releaseObject(app);
                    //return View("Index", "TaskDetailOld");     //change this to the TaskDetailController                  
                    //}
                }   //end of right file type: 'csv', 'xls', or 'xlsx'
                else
                {
                    ViewBag.Error = "File type is incorrect. Select file type with .xls or .xlsx";
                    return View("Index");
                }
                ViewBag.Success = "Upload was Successful!";
                return RedirectToAction("Index");
            }   //end of else
        }   //end of if

        /** Garbage Collect - when excel file is finished for reading/querying! **/

AprimoTaskViewer/Views/TaskDetailOld/Create.cshtml
@model AprimoTaskViewer.Models.TaskDetailOld

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailOld</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AprimoTaskViewer/Views/TaskDetailOld/Delete.cshtml
@model AprimoTaskViewer.Models.TaskDetailOld

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskDetailOld</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AprimoTaskViewer/Views/TaskDetailOld/Details.cshtml
@model AprimoTaskViewer.Models.TaskDetailOld

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaskDetailOld</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaskDetailId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AprimoTaskViewer/Views/TaskDetailOld/Edit.cshtml
@model AprimoTaskViewer.Models.TaskDetailOld

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailOld</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaskDetailId)

        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AprimoTaskViewer/Views/TaskDetailOld/Index.cshtml
@model IEnumerable<AprimoTaskViewer.Models.TaskDetailOld>
@using AprimoTaskViewer.Helpers;

@{
    ViewBag.Title = "Old Tasks";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

                        @*('Import' action method, 'TaskDetailOld' Controller)*@ 
@using (Html.BeginForm("Import", "TaskDetailOld", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <span><b> Excel File </b></span>
         <input type = "file" name = "excelfile" />
            <br> @Html.Raw(ViewBag.Error)
            @*@Html.DropDownList("statusId", ViewBag.StatusId as SelectList, "Select Status")*@
            <input type = "submit" value = "Import" class="btn btn-primary" />
            <br><br>
}

       @*('Search' action method, 'TaskDetailOld' Controller)*@
@using (Html.BeginForm("Search", "TaskDetailOld"))
{
    @*input String 'SearchBox' into Action 'Search' - StudentController*@
    @Html.Editor("SearchBox")           @*textbox*@
    <input type="submit" value="Search" />  @*Submit - button ("Search")*@
    @Html.DropDownList("dateRangeId", ViewBag.DateHistory as SelectList, "Select Date History")
}
<br>

 @using (Html.BeginForm("deleteRow", "TaskDetailOld", FormMethod.Post))
 {
     @*CSS3 - alternate row colors*@
    <style>
        tr:nth-child(odd) {
            background-color: #eee;
        }

        tr:nth-child(even) {
            background-color: #fff;
        }
    </style>
    @*@Html.DropDownList("statusId", ViewBag.StatusId as SelectList, "Select Status")*@
           <table class="table">
              
               <tr>
                   <th>
                       Select
                   </th>
                   <th> 
                       @Html.ActionLink("Manager", "Index", new { sortOrder = ViewBag.ManagerSortParm }) 
                   </th>
                   <th>
                       @Html.DisplayNameFor(model => model.status.StatusName)
                   </th>
                   <th>
                       @Html.ActionLink("Begin Date", "Index", new { sortOrder = ViewBag.BeginDateSortParm })
                   </th>

                   <th>
                       @Html.DisplayNameFor(model => model.EndDate)
                   </th>
                   <th>
                       @Html.ActionLink("Task Name", "Index", new { sortOrder = ViewBag.TaskNameSortParm })
                   </th>
                   <th>
                       @Html.ActionLink("Frame #", "Index", new { sortOrder = ViewBag.FrameNumberSortParm })
                   </th>

                   <th>
                       @Html.ActionLink("Aprimo #", "Index", new { sortOrder = ViewBag.AprimoSortParm })
                   </th>
                   <th>
                   </th>
               </tr>
                   @*<tbody>
                       @Html.EditorForModel()
                   </tbody>*@
               @foreach (var item in Model)
               {
                   <tr>
                       <td>
                           <input type="checkbox" name="aprimoRecordDeletebyId" id="aprimoRecordDeletebyId" value="@item.TaskDetailId" />
                       </td>
                       <td>
                           @Html.DisplayFor(modelItem => item.employee.ManagerName)
                           @* @Model.employee.ManagerName*@
                       </td>
                       <td>
                           @Html.DisplayFor(modelItem => item.status.StatusName)
                       </td>
                       <td>
                           @Html.DisplayFor(modelItem => item.BeginDate)
                       </td>
                       <td>
                           @Html.DisplayFor(modelItem => item.EndDate)
                       </td>
                       <td>
                           @Html.Truncate(item.TaskName, 20)
                       </td>
                       <td>

                           @Html.DisplayFor(modelItem => item.FrameNumber)
                       </td>
                       <td>
                           @Html.DisplayFor(modelItem => item.AprimoNumber)
                       </td>
                       <td>
                           @Html.ActionLink("Edit", "Edit", new { id = item.TaskDetailId }) |
                           @Html.ActionLink("Details", "Details", new { id = item.TaskDetailId }) |
                           @Html.ActionLink("Delete", "Delete", new { id = item.TaskDetailId })
                       </td>
                   </tr>
               }

           </table>
        <input type="submit" value="Delete Selected" class="btn btn-primary" />
 }