AprimoTaskViewer/Models/TaskDetailNew.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailNew : TaskDetail
    {
        [Display(Name = "Begin Date")]
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime BeginDate { get; set; }

        [Display(Name = "End Date")]
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
    }
}

AprimoTaskViewer/Controllers/TaskDetailNewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace AprimoTaskViewer.Models
{
    public class TaskDetailNewController : Controller
    {
        //Get instance and access of the 'TaskContext' database datatables
        private TaskContext db = new TaskContext();

        [HttpPost]
        public ActionResult deleteRow(IEnumerable<int> aprimoRecordDeletebyId)
        {
            //loop through each selected checkbox and pass this 'id' to selected Datatable rows
            foreach (var id in aprimoRecordDeletebyId)
            {
                var aprimo = db.OldTasks.Single(s => s.TaskDetailId == id);

                db.OldTasks.Remove(aprimo);
            }
            db.SaveChanges();   //after all selected check-boxed data rows are deleted - save changes to database
            return RedirectToAction("Index");
        }

        public ActionResult Search(string SearchBox)
        {
            var newtasks = from t in db.NewTasks select t;
            var newtasks2 = from z in db.NewTasks select z;

            DateTime searchDateNew;

            if (!String.IsNullOrEmpty(SearchBox))
            {
                //See if it is a DateTime format String - boolean
                //If true: searchDateNew stores 'SearchBox' date value
                bool isDateSearch = DateTime.TryParse(SearchBox, out searchDateNew);

                //DateSearch = true --> find 'Date' entered
                if (isDateSearch)
                {
                    newtasks = newtasks.Where(s => s.BeginDate.Equals(searchDateNew)
                                              ||s.EndDate.Equals(searchDateNew));
                }

                //execute if not DateTime format
                else
                {
                    int value;
                    if (int.TryParse(SearchBox, out value))
                    {
                        newtasks2 = from z in db.NewTasks
                                   where
                                        z.FrameNumber.ToString().Equals(SearchBox)
                                        || z.AprimoNumber.ToString().Equals(SearchBox)
                                   //|| z.ManagerId.Equals(SearchBox)
                                   //|| z.StatusId.Equals(SearchBox)
                                   select z;
                        return View("Index", newtasks2.ToList());
                    }

                    if (!int.TryParse(SearchBox, out value))
                    {
                        newtasks = from t in db.NewTasks
                                   where
                                       t.TaskName.Contains(SearchBox)
                                       || t.employee.ManagerName.Contains(SearchBox)  //'ManagerName' employee (nav. property)
                                       || t.status.StatusName.Contains(SearchBox)   //'StatusName' status (nav. property)
                                   select t;
                    }
                }
            }

            newtasks = newtasks.AsQueryable().OrderBy("ManagerId ASC, StatusId ASC, BeginDate ASC, FrameNumber ASC");
            //Return List of Tasks Data Rows Based on:
            //Date (boolean) or Textbox String
            return View("Index", newtasks.ToList());    //(Task Index Page, list of tasks) 
        }

        // GET: TaskDetailNew
        //User sees list of 'New Tasks' When clicking on 'New Tasks' Tab Header on the Site
        public ActionResult Index()
        {
            ViewBag.DateHistory = new SelectList(db.DateHistory, "DateRangeId", "DateHistory");
            var newtasks = db.NewTasks.Include(t => t.employee).Include(t => t.status);
            newtasks = newtasks.AsQueryable().OrderBy("ManagerId ASC, StatusId ASC, BeginDate ASC, FrameNumber ASC");
            return View(newtasks.ToList());
        }

        // GET: TaskDetailNew/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskDetailNew taskDetailNew = db.NewTasks.Find(id);
            if (taskDetailNew == null)
            {
                return HttpNotFound();
            }
            return View(taskDetailNew); //Don't need '.ToList()' - only one object/instance of a New Task is being returned back
        }

        // GET: TaskDetailNew/Create
        public ActionResult Create()
        {
            //Calls TaskDetailNewController > Create.cshtml 
            //Enable a DropDownList - Nothing is Selected  (default setting)
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName");    //KEY: ManagerId;  Value: ManagerName
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName");       //KEY: StatusId;  Value: StatusName
            return View();
        }

        // POST: TaskDetailNew/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskDetailId,BeginDate,EndDate,TaskName,FrameNumber,AprimoNumber,ManagerId,StatusId")] TaskDetailNew taskDetailNew)
        {
            if (ModelState.IsValid)
            {
                db.NewTasks.Add(taskDetailNew);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //Save Previous 'ManagerName' and 'Status' selected
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailNew.ManagerId); 
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailNew.StatusId);
            return View(taskDetailNew);
        }

        // GET: TaskDetailNew/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaskDetailNew taskDetailNew = db.NewTasks.Find(id);
            if (taskDetailNew == null)
            {
                return HttpNotFound();
            }

            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailNew.ManagerId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailNew.StatusId);
            return View(taskDetailNew);
        }

        // POST: TaskDetailNew/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskDetailId,BeginDate,EndDate,TaskName,FrameNumber,AprimoNumber,ManagerId,StatusId")] TaskDetailNew taskDetailNew)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taskDetailNew).State = EntityState.Modified;
                db.SaveChanges();

                //Move 'Edit' record to 'CancelledTasks' 
                //Cancelled = '3'
                if (taskDetailNew.StatusId == 3)
                {
                    TaskDetailCancel taskDetailCancel = new TaskDetailCancel();

                    taskDetailCancel.TaskName = taskDetailNew.TaskName;
                    taskDetailCancel.FrameNumber = taskDetailNew.FrameNumber;
                    taskDetailCancel.AprimoNumber = taskDetailNew.AprimoNumber;
                    taskDetailCancel.ManagerId = taskDetailNew.ManagerId;
                    taskDetailCancel.StatusId = taskDetailNew.StatusId;
                    taskDetailCancel.employee = taskDetailNew.employee;
                    taskDetailCancel.status = taskDetailNew.status;

                    db.CancelTasks.Add(taskDetailCancel);
                    db.NewTasks.Remove(taskDetailNew);
                    db.SaveChanges();
                  //  return View("TaskDetailCancel/Index", taskDetailCancel);
                }

                //Move 'Edit' record to 'OldTasks' 
                //Running = '4'; Completed = '5'
                if (taskDetailNew.StatusId == 4 || taskDetailNew.StatusId == 5)
                {
                    TaskDetailOld taskDetailOld = new TaskDetailOld();

                    taskDetailOld.TaskName = taskDetailNew.TaskName;
                    taskDetailOld.FrameNumber = taskDetailNew.FrameNumber;
                    taskDetailOld.AprimoNumber = taskDetailNew.AprimoNumber;
                    taskDetailOld.BeginDate = taskDetailNew.BeginDate;
                    taskDetailOld.EndDate = taskDetailNew.EndDate;
                    taskDetailOld.ManagerId = taskDetailNew.ManagerId;
                    taskDetailOld.StatusId = taskDetailNew.StatusId;
                    taskDetailOld.employee = taskDetailNew.employee;
                    taskDetailOld.status = taskDetailNew.status;

                    db.OldTasks.Add(taskDetailOld);
                    db.NewTasks.Remove(taskDetailNew);
                    db.SaveChanges();
                    //return View("TaskDetailOld/Index", taskDetailOld);
                }
                return RedirectToAction("Index");
            }
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "ManagerName", taskDetailNew.ManagerId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", taskDetailNew.StatusId);
            return View(taskDetailNew);
        }

        // GET: TaskDetailNew/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {

AprimoTaskViewer/Views/TaskDetailNew/Create.cshtml
@model AprimoTaskViewer.Models.TaskDetailNew

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailNew</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @*@Value = Model.BeginDate.ToString("MM/dd/yyyy"),*@ @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @*@Value = Model.EndDate.ToString("MM/dd/yyyy"),*@ @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@*@section scripts {

<script type="text/javascript">
    $(function () {

     $('#AnnualMeetingDate').datetimepicker({

      defaultDate: '@Model.BeginDate',
      format: 'L',
      showClose: true,
      showClear: true,
      toolbarPlacement: 'top'

     });

     $('#AnnualMeetingDate').datetimepicker({

          defaultDate: '@Model.EndDate',
          format: 'L',
          showClose: true,
          showClear: true,
          toolbarPlacement: 'top'
      });
  });
</script>
}*@

AprimoTaskViewer/Views/TaskDetailNew/Delete.cshtml
@model AprimoTaskViewer.Models.TaskDetailNew

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskDetailNew</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AprimoTaskViewer/Views/TaskDetailNew/Details.cshtml
@model AprimoTaskViewer.Models.TaskDetailNew

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaskDetailNew</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrameNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrameNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AprimoNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AprimoNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaskDetailId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AprimoTaskViewer/Views/TaskDetailNew/Edit.cshtml
@model AprimoTaskViewer.Models.TaskDetailNew

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaskDetailNew</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaskDetailId)

        <div class="form-group">
            @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrameNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FrameNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprimoNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AprimoNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AprimoNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AprimoTaskViewer/Views/TaskDetailNew/Index.cshtml
@model IEnumerable<AprimoTaskViewer.Models.TaskDetailNew>
@using AprimoTaskViewer.Helpers;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

           @*('Search' action method, Controller)*@
 @using (Html.BeginForm("Search", "TaskDetailNew"))
 {
     @*input String 'SearchBox' into Action 'Search' - StudentController*@
     @Html.Editor("SearchBox")           @*Name of textbox*@
     <input type="submit" value="Search" />  @*Submit - button ("Search")*@
            @*@Html.DropDownList("DateDropDown", ViewBag.DateHistory as SelectList, "Select Date History")
            @Html.DropDownListFor(M => M.DateRange, new SelectList(Model.DateRange, "Value", "Text"))*@
     }
<br>

@using (Html.BeginForm("deleteRow", "TaskDetailNew", FormMethod.Post))
{
    @*CSS3 - alternate row colors*@
    <style>
        tr:nth-child(odd) {
            background-color: #eee;
        }

        tr:nth-child(even) {
            background-color: #fff;
        }
    </style>
    <table class="table">
        <tr>
            <th>
                Select
            </th>
            <th>
                @Html.DisplayNameFor(model => model.employee.ManagerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status.StatusName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeginDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrameNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AprimoNumber)
            </th>
            <th></th>
        </tr>
        @*<tbody>
            @Html.EditorForModel()
        </tbody>*@
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="aprimoRecordDeletebyId" id="aprimoRecordDeletebyId" value="@item.TaskDetailId" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.employee.ManagerName)
                    @* @Model.employee.ManagerName*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status.StatusName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BeginDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.Truncate(item.TaskName, 20)
                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.FrameNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AprimoNumber)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.TaskDetailId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.TaskDetailId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.TaskDetailId })
                </td>
            </tr>
        }

    </table>
    <input type="submit" value="Delete Row(s)" />
}